apiVersion: v1
kind: Service
metadata:
  name: flask-service
  namespace: backend
spec:
  ports:
    - port: 5000
      targetPort: 5000
  selector:
    app: flask-app
    role: flask-app
  type: LoadBalancer