apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app
  namespace: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flask-app
      role: flask-app
  template:
    metadata:
      labels:
        app: flask-app
        role: flask-app
    spec:
      containers:
        - name: flask-app-container
          image: <your-docker-image>  # Replace with your image name
          ports:
            - containerPort: 5000
          env:
            - name: DATABASE_URL
              value: "postgresql://postgres:password@postgres.postgres.svc.cluster.local:5432/mydatabase"
