apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app
  namespace: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask-app
      role: flask-app
  template:
    metadata:
      labels:
        app: flask-app
        role: flask-app
    spec:
      containers:
        - name: flask-app-container
          image: us-central1-docker.pkg.dev/kxn-dev-432901/flask-application/docker-flask:13
          ports:
            - containerPort: 5000
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: backend-database-secrets
                  key: postgres-user
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: backend-database-secrets
                  key: postgres-password
          readinessProbe:
            httpGet:
              path: /
              port: 5000
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: 5000
            initialDelaySeconds: 10
            periodSeconds: 20

