apiVersion: v1
kind: Secret
metadata:
  name: backend-database-secrets
  namespace: backend
type: Opaque
data:
  postgres-user: cG9zdGdyZXM=       # base64 encoded value of 'postgres'
  postgres-password: ZGluZXNoc2Fp 
