apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-database-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/dineshsai14211/CRM-manifest-files
    targetRevision: main
    path: ./database  # Path to database resources
  destination:
    server: https://kubernetes.default.svc
    namespace: database  # Specify the database namespace
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: true
    syncOptions:
      - CreateNamespace=true
  revisionHistoryLimit: 5
