# postgres-secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: postgres
type: Opaque
data:
  postgres-user: cG9zdGdyZXM=     # base64 encoded value of 'postgres'
  postgres-password: ZGluZXNoc2Fp 
